# Generated by Django 4.1.3 on 2022-11-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_author_pseudonym"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"], "verbose_name_plural": "cities"},
        ),
    ]
