# Generated by Django 4.1.3 on 2022-11-10 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_alter_city_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="authors",
            field=models.ManyToManyField(
                related_name="authors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
