# Generated by Django 4.1.3 on 2022-11-10 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_alter_publication_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="authors",
            field=models.ManyToManyField(
                related_name="publications", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
